[package]
name = "videoproxy-rs"
version = "0.1.0"
authors = ["suconghou <suconghou@gmail.com>"]
edition = "2018"


[dependencies]
actix-web =  { version = "3", features=["rustls"] }
actix-files = "0.5"
serde = "1"
serde_json = "1"
lazy_static = "1"
tokio = { version = "1", features = ["full"] } 